default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: kiva_snapshot_development

test:
  <<: *default
  database: kiva_snapshot_test

production:
  <<: *default
  database: kiva_snapshot_production
  password: <%= ENV['DATABASE_URL'] %>
